spring:
  application:
    name: Backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379
